### ISSUE TITLE
64-bit ARM

### ISSUE THREAD

**Issue by jwillikers** [flathub/com.sublimemerge.App#15]
Sublime Merge has been releasing packages for 64-bit ARM Linux on [their discord server](https://forum.sublimetext.com/t/sublime-text-discord-server/26063), publishing links to new packages in the *announcements* channel. The latest ARM edition of Sublime Merge is available here: https://download.sublimetext.com/sublime-merge_build-2041_arm64.deb

Would it be possible to add support for 64-bit ARM?

**Comment by ptomato** [comment]
Sure, it seems like what would need to be done is add the arm64 sources in https://github.com/flathub/com.sublimemerge.App/blob/master/com.sublimemerge.App.yaml (for git-lfs as well) and then add it in https://github.com/flathub/com.sublimemerge.App/blob/master/flathub.json. I would happily accept a pull request for this.

**Comment by jwillikers** [comment]
@ptomato I can do a PR for this. 👍
