### ISSUE TITLE
Needs a 64x64 and 128x128 icon

### ISSUE THREAD

**Issue by jgarciao** [flathub/com.sublimemerge.App#2]
Flathub.org (the website) gets the information about the apps from the appstream.xml file generated in the ostree repo. You can see the contents in your computer opening this file: /var/lib/flatpak/appstream/flathub/x86_64/active/appstream.xml

This app is not appearing in the website because it has some issues in the appstream information:
 -  there is no `<icon>` tag for 64x64 and 128x128

**Comment by yilmzfurkan** [comment]
Yeah just noticed that Sublime Merge is available as flatpak when I was looking around in Flathub Builder. Was searching it on Flathub it doesn't exists. @ptomato any news about this?

**Comment by ptomato** [comment]
That makes sense, I forgot about this. Would anyone like to make a pull request? The 64x64 icon should be possible to create just by downsizing the existing 128x128 one.
