### ISSUE TITLE
Runtime no longer includes clang-format

### ISSUE THREAD

**Issue by ptomato** [flathub/com.sublimemerge.App#32]
The upgrade to freedesktop SDK 21.08 lost clang-format from the runtime, it was present in 20.08. I think some C++ projects use clang-format as a commit hook; at least I do, and I copied the idea from other projects :smile: 

Maybe we can include clang-format in the manifest or maybe there is some freedesktop SDK extension that brings it in.

**Comment by jwillikers** [comment]
Yeah, it would also be nice to have `pre-commit`, too.
